### PR TITLE
Feat: add DeepMD pretrain model

### PR DESCRIPTION
**Pull request by anyangml**
Hi Yuan,

My name is Anyang, and I'm a developer at DeepModeling. Our team is developing a series of models within the DeepMD-kit framework. We are keen to contribute to your repository and, as an initial offering, we've included a pre-trained model on 'MPtrj' within this pull request.

Should you require any additional information or details regarding our contribution, please don't hesitate to reach out.

Best regards,

Anyang

### CODE REVIEW

**Comment by chiang-yuan** [comment]
Hi @anyangml thanks so much for the PR. I will add some dependencies and run some of the simple benchmark (e.g. diatomic curves) before merging this. :)

**Comment by anyangml** [comment]
Let me know if you need any help with the installation.

**Comment by chiang-yuan** [comment]
Hey @anyangml sorry for late response on this. Made some changes to merge the latest main into it. Could you try installing 
 deepmd andd adding dependencies into `test` in pyproject.toml and see if it can pass the test?

https://github.com/atomind-ai/mlip-arena/blob/aa496c250d371273ebaec69512936cf82563ad4f/pyproject.toml#L60-L72

**Comment by anyangml** [comment]
I noticed that there is a Pytorch version mismatch, and maybe we can downgrade the Deepmd version.  I will look into that and run some test.

**Comment by chiang-yuan** [comment]
thanks @anyangml I will merge this merge first. Haven't run any benchmark yet (hence will not show on main page) but the model has no conflict with other package and can be used already.

**Pull request merged**
